name: Portfolio Update

on:
  repository_dispatch:
    types: [project-update]

jobs:
  update-portfolio:
    runs-on: ubuntu-latest

    steps:
      - name: Show repo url
        run: echo "${{ github.event.client_payload.repo_url }}"

      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.PORTFOLIO_APP_ID }}
          private-key: ${{ secrets.PORTFOLIO_APP_PRIVATE_KEY }}

      - name: Download portfolio update
        run: |    
          REPO_PATH=$(echo "${{ github.event.client_payload.repo_url }}" | sed -E 's|git://github.com/||' | sed -E 's|\.git$||')

          curl -H "Authorization: token ${{ steps.app-token.outputs.token }}" \
               -H "Accept: application/vnd.github.v3.raw" \
               -L "https://api.github.com/repos/${REPO_PATH}/contents/portfolio-update.md" \
               -o source-portfolio-update.md