name: Portfolio Update

on:
  repository_dispatch:
    types: [project-update]

jobs:
  update-portfolio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout automation repository
        uses: actions/checkout@v7.0.0

      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.PORTFOLIO_APP_ID }}
          private-key: ${{ secrets.PORTFOLIO_APP_PRIVATE_KEY }}

      - name: Checkout portfolio repository
        uses: actions/checkout@v7.0.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: Dron3xx-End-to-End/aws-cloud-website
          path: aws-cloud-website

      - name: Show repo url
        run: echo "${{ github.event.client_payload.repo_url }}"

      - name: Download portfolio update
        run: |    
          REPO_PATH=$(echo "${{ github.event.client_payload.repo_url }}" | sed -E 's|git://github.com/||' | sed -E 's|\.git$||')

          curl -H "Authorization: token ${{ steps.app-token.outputs.token }}" \
               -H "Accept: application/vnd.github.v3.raw" \
               -L "https://api.github.com/repos/${REPO_PATH}/contents/portfolio-update.md" \
               -o source-portfolio-update.md

          cat source-portfolio-update.md

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4

      - name: Update portfolio repository
        run: | 
          python -m scripts.main source-portfolio-update.md \
          aws-cloud-website/index.html \
          ${{ github.event.client_payload.repo_url }}

      - name: Commit and push updated portfolio
        env:
          GITHUB_USER: "github-actions[bot]"
          GITHUB_EMAIL: "github-actions[bot]@users.noreply.github.com"
        run: |
          git config user.name "${{ env.GITHUB_USER }}"
          git config user.email "${{ env.GITHUB_EMAIL }}"

          git diff
          ls -la
          ls -la js/
          git add index.html js/language.js

          if git diff-index --quiet HEAD --; then
            echo "Brak zmian do wdrożenia."
          else
            git commit -m "Added new project card"
            git push
          fi
        working-directory: ./aws-cloud-website